version: "3.9"

services:
  api:
    build: .
    container_name: hono-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dinacom
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: hono-db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dinacom
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
